config/routes.rb
Rails.application.routes.draw do
  root 'store#index', as: 'store'
  
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  
  
  resources :products do
    get :who_bought, on: :member
  end
  
  resources :line_items do
  	member do
  		post 'decrement'
  		post 'increment'
  	end
  end

  resources :carts

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
  	product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create, :destroy, :decrement, :increment]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find_by(id: params[:product_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url, notice: "#{product.title} was added to your cart." }
        format.js { @current_item = @line_item}
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /line_items/1/decrement
  def decrement
    @line_item = LineItem.find_by(id: params[:id])
    @line_item.quantity -= 1
    @line_item.save
    if @line_item.quantity == 0
      @line_item.destroy
    end
    respond_to do |format|
      format.js {@current_item = @line_item}
      format.html {redirect_to store_url, notice: 'Removed item from cart'}
      format.json {head :no_content}
    end
  end

   # POST /line_items/1/increment
  def increment
    @line_item = LineItem.find_by(id: params[:id])
    @line_item.quantity += 1
    @line_item.save
    respond_to do |format|
      format.js {@current_item = @line_item}
      format.html {redirect_to store_url, notice: 'Added item to cart'}
      format.json {head :no_content}
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.js { @current_item = @line_item}
      format.html { 
        redirect_to cart_url(@line_item.cart), 
        notice: "#{@line_item.product.title} was removed from your cart." 
      }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
		<% if line_item == @current_item %>
		<tr class="current_item">
		<% else %>
		<tr>
		<% end %>
		<td class="increment-quantity">
			<%= button_to '&#9650;'.html_safe, increment_line_item_path(line_item), class: 'button-increment-quantity', title: 'Add 1 to Qty', remote: true %>
		</td>
		<% if line_item.quantity > 1 %>
			<td class="decrement-quantity">
				<%= button_to '&#9660;'.html_safe, decrement_line_item_path(line_item), class: 'button-decrement-quantity', title: 'Remove 1 from Qty', remote: true %>
			</td>
		<% end %>
		<td style="width: 20px;"><%= line_item.quantity %> &times;</td>
		<td><%= truncate(line_item.product.title, length: 15) %></td>
		<td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
		<td class="remove_item">
			<%= button_to "&times;".html_safe, line_item, class: 'button-remove-item', method: :delete, 
					data: {confirm: "Remove #{line_item.product.title} from cart?"}, remote: true %>
		</td>
	</tr>
	

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s\n", line_item.quantity, 
	truncate(line_item.product.title, length: 50)) %>

app/views/line_items/create.js.erb
$('#notice').hide();
if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000);}

$('#cart').html("<%= escape_javascript render(@cart) %>");
$("#cart .current_item").css({'background-color': '##f9df99'}).
	animate({'background-color': '#efefef'}, 1000);

app/views/line_items/decrement.js.erb
if ($('#cart tr').length < 1) { $('#cart').hide('blind', 1000);}

$('#cart').html("<%= escape_javascript render(@cart) %>");
$("#cart tr.current_item").css({'background-color': '##f9df99'}).
	animate({'background-color': '#efefef'}, 1000);

app/views/line_items/destroy.js.erb
if ($('#cart tr').length < 3) { $('#cart').hide('blind', 1000);}

$('#cart').html("<%= escape_javascript render(@cart) %>");
$("#cart tr").css({'background-color': '##f9df99'}).
	animate({'background-color': '#efefef'}, 1000);

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/increment.js.erb
$('#cart').html("<%= escape_javascript render(@cart) %>");
$("#cart .current_item").css({'background-color': '##f9df99'}).
	animate({'background-color': '#efefef'}, 1000);

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>